quality: 90

features:
  prometheus:
    enabled: true
    namespace: imgproxy

resources:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - thumbnail.kiyomi.io
  pod:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8081"