version: "3.5"

volumes:
  sp_pg:
    external: true

services:
  pg:
    container_name: sp_pg
    restart: on-failure
    build:
      context: postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DATABASE: simp
      POSTGRES_USER: postgres
    volumes:
      - sp_pg
