version: "3.2"

volumes:
  # not important to get indexed immediately
  sp_pg:
    external: true

services:
  redis:
    image: redis
    container_name: sp_redis
    ports:
      - 6300:6379
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:3.8.9-management
    container_name: sp_rabbitmq
    ports:
      - 3333:5672
      - 15672:15672
  pg:
    container_name: sp_pg
    restart: on-failure
    build:
      context: postgres
      dockerfile: Dockerfile
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DATABASE: simp_pics
      POSTGRES_USER: postgres
    volumes:
      - sp_pg:/var/lib/postgresql/data
