- set_fact:
    network: &network
      networks:
        - name: "{{ docker_network_name }}"
    restart_rules: &restart_rules
      restart_policy: always
    traefik_labels: &traefik
      traefik.enable: "true"
      traefik.docker.network: "{{ docker_network_name }}"
    healthcheck: &healthcheck_opts
      interval: 10s
      timeout: 5s
      retries: 5

- name: Ensure network created
  docker_network:
    name: "{{ docker_network_name }}"

- name: Ensure traefik is in network
  docker_network:
    name: "{{ docker_network_name }}"
    containers:
      - traefik

- name: Create database volume
  docker_volume:
    name: "{{ postgres.name }}-volume"

- name: Ensure Docker database is running
  docker_container:
    name: "{{ postgres.name }}"
    image: xetera/simp-pics-postgres
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
    volumes:
      - "{{ postgres.name }}-volume"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    ports:
      - 5430:5432
    env:
      POSTGRES_USER: "{{ postgres.username }}"
      POSTGRES_PASSWORD: "{{ postgres.password }}"
      POSTGRES_DB: "{{ postgres.database }}"
    # labels:
    #   traefik.enable: "true"
    #   traefik.docker.network: "{{ docker_network_name }}"
    #   traefik.tcp.services.simp_postgres.loadbalancer.server.port: "5432"
    #   traefik.tcp.routers.simp_postgres.entrypoints: postgres
    #   traefik.tcp.routers.simp_postgres.rule: HostSNI(`db.simp.pics`)
    #   traefik.tcp.routers.simp_postgres.service: simp_postgres
    healthcheck:
      <<: *healthcheck_opts
      test: "pg_isready -U {{ postgres.username }}"

- name: Creating Webserver
  docker_container:
    name: "{{ simp.name }}"
    image: xetera/simp-pics
    pull: true
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "{{ docker_network_name }}"
      traefik.http.routers.simp.rule: "Host(`{{ domain }}`)"
      traefik.http.routers.simp.tls.certresolver: cert
      traefik.http.routers.simp.tls: "true"
      traefik.http.routers.simp.entrypoints: websecure
      traefik.http.services.simp.loadbalancer.server.port: "{{ simp.port }}"
      traefik.http.services.simp.loadbalancer.healthcheck.path: /api/health
    env:
      WASABI_ACCESS_KEY: "{{ simp.wasabi_access_key }}"
      WASABI_SECRET: "{{ simp.wasabi_secret_key }}"
      NODE_ENV: production
      POSTGRES_URL: "{{ postgres.url }}"
      DISCORD_ID: "{{ simp.discord.id }}"
      DISCORD_SECRET: "{{ simp.discord.secret }}"
      NEXTAUTH_URL: "{{ domain }}"
      NEXT_PUBLIC_BASE_URL: "https://{{ domain }}"
      NEXT_PUBLIC_BASE_URL_CDN: "https://my.simp.pics"
      PORT: "{{ simp.port }}"
    # healthcheck:
    #   <<: *healthcheck_opts
    #   test: curl -sS http://127.0.0.1/health || exit 1
