# This config is just an example for development
global:
  scrape_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: site
    scrape_interval: 5s
    static_configs:
      - targets:
          - localhost:3000
  # game server
  - job_name: dubu
    scrape_interval: 5s
    static_configs:
      - targets:
          - localhost:9002
  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
      - targets:
          - localhost:9090
  - job_name: imgproxy
    scrape_interval: 10s
    static_configs:
      - targets:
          - localhost:3421
