docker_network_name: simppicsnet

domain: "simp.pics"

ssh:
  username:

simp:
  name: "simp_pics"
  port: "3000"
  wasabi_access_key: "{{ lookup('env', 'WASABI_ACCESS_KEY') }}"
  wasabi_secret_key: "{{ lookup('env', 'WASABI_SECRET_KEY') }}"
  discord:
    id: "{{ lookup('env', 'DISCORD_ID') }}"
    secret: "{{ lookup('env', 'DISCORD_SECRET') }}"

postgres_name: simp_postgres
postgres_database: simp_pics
postgres_username: postgres
postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"

postgres:
  name: "{{ postgres_name }}"
  url: "postgres://{{ postgres_username }}:{{ postgres_password }}@{{ postgres_name }}:5432/{{ postgres_database }}"
  datadog_username: datadog
  datadog_password: "{{ lookup('env', 'DATADOG_POSTGRES_PASSWORD') }}"
  password: "{{ postgres_password }}"
  username: "{{ postgres_username }}"
  database: "{{ postgres_database }}"
