name: Test and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: xetera/simp-pics
          build_extra_args: --build-arg NEXT_PUBLIC_BASE_URL=https://simp.pics --build-arg NEXT_PUBLIC_BASE_URL_CDN=https://my.simp.pics
  postgres:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          context: postgres
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: xetera/simp-pics-postgres
  deploy:
    if: github.ref == 'refs/heads/main'
    needs:
      - build
      - postgres
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==2.9.2 requests
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh/
          chmod 700 ~/.ssh/
          echo "$key" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          stat ~/.ssh/id_rsa
        env:
          key: ${{ secrets.SSH_KEY }}
      - name: SSH into machine?
        run: "ssh -vvv -o StrictHostKeyChecking=no root@$ip"
        env:
          ip: ${{ secrets.HOST_IP }}
      - name: Install paramiko
        run: pip install paramiko
      - name: Run ansible playbook
        run: cd ansible && ansible-playbook playbook.yaml -i "${{ secrets.HOST_IP }}," -vvvv -c paramiko -e "ansible_user=root"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          DISCORD_REDIRECT_URL: ${{ secrets.DISCORD_REDIRECT_URL }}
          DISCORD_CALLBACK_URL: ${{ secrets.DISCORD_CALLBACK_URL }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          RESTIC_PASSWORD: ${{ secrets.RESTIC_PASSWORD }}
          B2_ACCOUNT_ID: ${{ secrets.B2_ACCOUNT_ID }}
          B2_ACCOUNT_SECRET: ${{ secrets.B2_ACCOUNT_SECRET }}
