"on":
  push:
    branches:
    - new-kiyomi
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Set Github tag
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: site/api/Dockerfile
        context: .
        push: true
        tags: xetera/kiyomi-api:latest
        cache-from: type=registry,ref=xetera/kiyomi-api:latest
        cache-to: type=inline
    - name: Update Porter App
      timeout-minutes: 20
      uses: porter-dev/porter-update-action@v0.1.0
      with:
        app: kiyomi-api
        cluster: "355"
        host: https://dashboard.getporter.dev
        namespace: default
        project: "662"
        tag: ${{ steps.vars.outputs.sha_short }}
        token: ${{ secrets.PORTER_TOKEN_662 }}
