name: PR Test
on:
  pull_request:
    paths:
      - site/**

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v1
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: xetera
          password: "${{ secrets.DOCKER_PASSWORD }}"
          dockerfile: site/Dockerfile
          context: .
          image_name: xetera/simp-pics
          push_image_and_stages: false
          build_extra_args: --build-arg NEXT_PUBLIC_BASE_URL=https://simp.pics --build-arg NEXT_PUBLIC_BASE_URL_CDN=https://my.simp.pics
