name: PR Test
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: localhost:5000/xetera/simp-pics:latest
