name: PR Test
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v1
      - uses: whoan/docker-build-with-cache-action@v5
        env:
          NEXT_PUBLIC_BASE_URL: https://simp.pics
        with:
          username: xetera
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: xetera/simp-pics
          push_image_and_stages: false
